venv:
	python3 -m pip install --upgrade pip
	python3 -m pip install virtualenv
	virtualenv VENV

install:
	python3 -m pip install --upgrade pip
	python3 -m pip install -r requirements.txt

run:
	jupyter notebook
